baseURL = "http://aaronsaunders.dk/"
languageCode = "en-us"
title = "Aaron's Blog"
theme = "ezhil"
paginate = 5

copyright = "Â© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "Personal Website and blog of Aaron Saunders"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

	# Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
  favicon = "/icons/myfavicon.ico"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aaronsaunders"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/aaronsaunders/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"


